apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets-service
  template:
    metadata:
      labels:
        app: assets-service
    spec:
      containers:
        - name: assets-service
          image: 079059455431.dkr.ecr.us-east-1.amazonaws.com/assets-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
            - containerPort: 9091
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FLASK_ENV
            - name: ASSETS_SERVICE_PORT
              value: "8001"
            - name: ASSETS_SERVICE_METRICS_PORT
              value: "9091"
            - name: PROMETHEUS_MULTIPROC_DIR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PROMETHEUS_MULTIPROC_DIR
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: FILES_SERVICE_URL
              value: http://files-service.default.svc.cluster.local:8002
---
apiVersion: v1
kind: Service
metadata:
  name: assets-service
spec:
  selector:
    app: assets-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP
